# Generated by Django 3.2.8 on 2021-10-19 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('RT', 'Remote')], default='FT', max_length=10)),
                ('experience', models.CharField(choices=[('t1', 'Less than 2 years'), ('t2', '2 years - 5 years'), ('t3', '5 years - 10 years'), ('t4', '10 years - 15 years'), ('t5', 'More than 15 years')], default='t1', max_length=10)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('logo', models.ImageField(default='default.png', upload_to='upload_images')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
